# TODO: ローカルでのAPIに対応したい
openapi: 3.0.1
info:
  title: Sample API
  description: API for a sample AWS SAM application written in Go
  version: 1.0.0

servers:
  - url: 'http://localhost:3000'

paths:
  /health:
    post:
      summary: Check the health of the application
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

components:
  schemas:
    Success:
      description: 成功の場合のレスポンス
      type: object
      properties:
        message:
          type: string
      required:
        - message
