AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-presentation
  
  Sample SAM Template for sam-app-presentation
Parameters:
  DBUser:
    Type: String
  DBHost:
    Type: String
  DBPass:
    Type: String
  DBName:
    Type: String
  LineUserId:
    Type: String
  DEEPLApiKey:
    Type: String
  OPENAIApiKey:
    Type: String
  ChannelSecret:
    Type: String
  ChannelToken:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: webhook/
      Handler: webhook
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DBUser: !Ref DBUser
          DBHost: !Ref DBHost
          DBPass: !Ref DBPass
          DBName: !Ref DBName
          ChannelSecret: !Ref ChannelSecret
          ChannelToken: !Ref ChannelToken
          OPENAIApiKey: !Ref OPENAIApiKey
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  HealthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: health/
      Handler: health
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  MigrateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: migrate/
      Handler: migrate
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /migrate
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DBUser: !Ref DBUser
          DBHost: !Ref DBHost
          DBPass: !Ref DBPass
          DBName: !Ref DBName
          DEEPLApiKey: !Ref DEEPLApiKey
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  SearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: search/
      Handler: search
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DBUser: !Ref DBUser
          DBHost: !Ref DBHost
          DBPass: !Ref DBPass
          DBName: !Ref DBName
          OPENAIApiKey: !Ref OPENAIApiKey
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  ScheduleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: schedule/
      Handler: shcedule
      Runtime: go1.x
      # Architectures:
      #   - x86_64
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DBUser: !Ref DBUser
          DBHost: !Ref DBHost
          DBPass: !Ref DBPass
          DBName: !Ref DBName
          DEEPLApiKey: !Ref DEEPLApiKey
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

Outputs:
  # TODO: デプロイ後のURLがわかるようにする
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhookAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  WebhookFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt WebhookFunction.Arn
  # WebhookFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt WebhookFunctionRole.Arn
