CREATE TABLE IF NOT EXISTS garbage_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  garbage_id VARCHAR(255) UNIQUE,
  garbage_master_id INT,
  category VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (garbage_master_id) REFERENCES garbage_masters(id)
);