AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-presentation
  
  Sample SAM Template for sam-app-presentation
Params:
  DB_USER:
    Type: String
  DB_HOST:
    Type: String
  DB_PASS:
    Type: String
  DB_NAME:
    Type: String
  LINE_USER_ID:
    Type: String
  DEEPL_API_KEY:
    Type: String
  OPENAI_API_KEY:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  HealthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: health/
      Handler: health
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /health
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  MasterUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: masteruser/
      Handler: masteruser
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /masteruser
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
          LINE_USER_ID: !Ref LINE_USER_ID
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  MasterGarbageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mastergarbage/
      Handler: mastergarbage
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mastergarbage
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  GarbageItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: garbageitem/
      Handler: garbageitem
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /garbageitem
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  GarbageItemDetailJaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: garbageitemdetail-ja/
      Handler: garbageitemdetail-ja
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /garbageitemdetail-ja
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  GarbageItemDetailEnFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: garbageitemdetail-en/
      Handler: garbageitemdetail-en
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /garbageitemdetail-en
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
          DEEPL_API_KEY: !Ref DEEPL_API_KEY
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  GPTSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: gpt-search/
      Handler: gpt-search
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /gpt-search
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  BleveSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bleve-search/
      Handler: bleve-search
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bleve-search
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  BlugeSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bluge-search/
      Handler: bluge-search
      Runtime: go1.x
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bluge-search
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_USER: !Ref DB_USER
          DB_HOST: !Ref DB_HOST
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

  # ScheduleFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: schedule-exec/
  #     Handler: shcedule-exec
  #     Runtime: go1.x
  #     # Architectures:
  #     #   - x86_64
  #     Events:
  #       # CatchAll:
  #       #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #       #   Properties:
  #       #     Path: /hello
  #       #     Method: GET
  #       ScheduleEvent:
  #         Type: Schedule
  #         Properties:
  #           Schedule: rate(1 minute)
  #     Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
  #       Variables:
  #         PARAM1: VALUE
  #     Role: arn:aws:iam::880843126767:role/go-academy-lambda

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldAPI:
  #   Description: "API Gateway endpoint URL for Prod environment for First Function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
